channel:
  id: 1656553601
  secret: 7ec43e5faf5c0b0f3ebd5db8c3aab219
  accessToken: >-
    nEiFR6u0BCod9lr/InFniRF/QAs4TbEHkHTNBOUK9VlWfhdsy8qcm2qcspoOMPo0FvnYZKELsN7cCe3iip/HCk8Iwmwo6FXBpBd+oCCuxmBLUQN73EuPVccK4lg8l05S3W/7xSAVhFhwb36HPWu1LY9PbdgDzCFqoOLOYbqAITQ=
