channel:
  id: 1656628068
  secret: 981de084d60af92347bd5591cc245729
  accessToken: >-
    PvTDSHiMI/RIxb2CxLtHVmgJOI4eHKxoFFGTvz4Jo3RtSFw8M/8pfNczhnw8Zs/timxgC8rgv/+RAlJczunR0jW70YU4dZENkULS+IhN7Db9d49l6HsOdGDz3iqrC9saWgJTy3XzWfxTUYin1L7dBY9PbdgDzCFqoOLOYbqAITQ=
