channel:
  id: 1656553601
  secret: 7ec43e5faf5c0b0f3ebd5db8c3aab219
  accessToken: >-
    CcBlOhtl+EkNZmR2SKPVCo+/FuhQmriyfr8xgMVA54fj7HN/P9GvRTTwDSfnd4lqFvnYZKELsN7cCe3iip/HCk8Iwmwo6FXBpBd+oCCuxmDh3tg3jl7/XYeZVx6Us7M9o09qEWSXFeMAtf8I/jKWqI9PbdgDzCFqoOLOYbqAITQ=
