channel:
  id: 1656628068
  secret: 981de084d60af92347bd5591cc245729
  accessToken: >-
    oUSINwlxxXsDho11nn7G5htK4kdyubWaTdRVNhcyeGJ7j/hAP35Nf1/3prAYyKJSimxgC8rgv/+RAlJczunR0jW70YU4dZENkULS+IhN7Dages/dnWBSYxg3egCd2Y/p0SyX9mLh3mGOA06YRKt67gdB04t89/1O/w1cDnyilFU=
